# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# some more aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias a='fasd -a'
alias aptgrep='sudo apt-cache search'
alias autoremove='sudo apt-get autoremove'
alias be='bundle exec'
alias cap='bundle exec cap'
alias d='fasd -d'
alias df='df -h'
alias e='emacsclient -t'
alias egrep='egrep --color=auto'
alias emacsdaemon='emacs --daemon'
alias f='fasd -f'
alias fgrep='fgrep --color=auto'
alias g='git'
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias gb='git branch'
alias grep='grep --color=auto'
alias install='sudo apt-get install'
alias mj='NODE_ENV=test mocha --compilers js:babel-core/register'
alias mycal='gcalcli --calendar "Marty Hu (Personal)" --calendar "marty@getprodigy.com"'
alias ogc='open -a Google\ Chrome'
alias purge='sudo apt-get purge'
alias rvm-restart='rvm_reload_flag=1 source '\''/Users/marty/.rvm/scripts/rvm'\'''
alias s='fasd -si'
alias sd='fasd -sid'
alias semacs='sudo emacs -nw'
alias sf='fasd -sif'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias z='fasd_cd -d'
alias zz='fasd_cd -d -i'
alias b='babel-node'
# alias saltstack='ssh -t master \''sudo salt \''*\'' state.apply\'''
# alias saltstaging='ssh -t master \''sudo salt \''*staging*\'' state.apply\'''
# alias vagrantprod='ENV=ec2 vagrant provision; and saltstack'
# alias vagrantstaging='ENV=ec2 vagrant provision; and saltstaging'
